### ISSUE TITLE
database migration foreign key error

### ISSUE THREAD

**Issue by codingpapa** [baddaralishah/online-store#1]
![ss](https://user-images.githubusercontent.com/28788372/32048361-b4bd4d1c-ba62-11e7-82ba-afd38b2ce1d3.png)

**Comment by MuhammadTalha944** [comment]
some times this happens in laravel during migrations.you can resolve your error as i did..
i just added a line before the foreign key
 Schema::create('user_questions', function (Blueprint $table) {
$table->integer('user_id')->unsigned();
$table->foreign('user_id')->references('id')->on('users');
}
